apiVersion: v1
kind: Service
metadata:
  name: reddit-service
spec:
  type: LoadBalancer
  selector:
    app: reddit
  ports:
  - port: 80          # the port GKE will expose externally
    targetPort: 8000  # your container’s FastAPI port

#spec:
#  type: NodePort
#  selector:
#    app: reddit
#  ports:
#  - port: 8000               # inside-cluster port
#    targetPort: 8000         # container’s port
#    nodePort: 30007          # exposes it on localhost:30007
